name: ğŸ¦‹ Lint static assets

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸŒ¿
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up Node.js ğŸŸ¢
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "22"

      - name: Install linters ğŸ“¦
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard eslint

      - name: Install dependencies ğŸ“¦
        run: |
          npm install

      - name: Lint HTML âœ…
        id: lint_html
        continue-on-error: true
        run: |
          npx htmlhint 'static/**/*.html'

      - name: Lint CSS âœ…
        id: lint_css
        continue-on-error: true
        run: |
          npx stylelint 'static/**/*.css' --config .stylelintrc.json

      - name: Lint JavaScript âœ…
        id: lint_js
        continue-on-error: true
        run: |
          npx eslint 'static/**/*.js'

      - name: Fail if any linter failed âŒ
        if: steps.lint_html.outcome == 'failure' || steps.lint_css.outcome == 'failure' || steps.lint_js.outcome == 'failure'
        run: |
          echo "One or more linters failed."
          exit 1
